apiVersion: v1
kind: Service
metadata:
  name: kayan
  labels:
    app: kayan
    app.kubernetes.io/name: kayan
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kayan
---
# Headless service for internal discovery
apiVersion: v1
kind: Service
metadata:
  name: kayan-headless
  labels:
    app: kayan
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kayan
